config/routes.rb
Rails.application.routes.draw do

  namespace :clients do
    get 'index'
    post 'create'
    post 'update'
    get 'edit'
    post 'update_factors'
  end

  get 'employees/index'

  get 'services/index'
  get 'servicios/:page' => 'services#index', as: :services
  post 'change_contable_code' => 'services#update_contable_code', as: :update_contable_code
  post '/nuevo_Servicio' => 'services#create', as: :create_service
  post '/borrar_Servicio' => 'services#delete', as: :delete_myservice
  get '/doctores' => 'doctors#index', as: :doctors

  get 'doctors/show'

  get 'doctors/new'

  get 'doctors/edit'
  post '/agregar_doctor' => 'doctors#create', as: :create_doctor
  post '/modificar_doctor' => 'doctors#update', as: :update_doctor
  post '/eliminar_doctor' => 'doctors#delete', as: :delete_doctor


  post '/agregar_especialidad' => 'doctors#create_speciality', as: :create_speciality

  get 'chat_csl/:page' => 'chat#index', as: :chat
  post 'agregarmensaje' => 'chat#add', as: :add_chat

  get 'admissions/new'
  #get 'admisiones/nuevo/:patient_id' => 'admissions#new', as: :new_admission
  get 'admissions/ready'
  get 'admision/ready/:authorization_id' => 'admissions#ready', as: :ready_admission
  post 'confirmar_admision' => 'admissions#confirm', as: :confirm_admission
  get 'admissions/index'

  get 'admission/new'


  get 'admission/ready'

  get 'admission/index'

  resources :providers

  get 'topic_sales/new'

  get 'topic_sales/ready'

  get 'cobertura/nuevo/:id' => 'coverage_sales#new', as: :new_coverage
  get 'cobertura/ready/:id' => 'coverage_sales#ready', as: :ready_coverage
  post 'confirmcobertura' => 'coverage_sales#confirm', as: :confirm_coverage
  post 'addcobertura' => 'coverage_sales#add', as: :add_coverage
  post 'cerrarcobertura' => 'coverage_sales#close', as: :close_coverage
  post 'borrarconsulta' => 'coverage_sales#delete', as: :delete_coverage
  post 'fastcoverage' => 'coverage_sales#fast_close', as: :fast_close

  get 'topico/nuevo/:id_authorization' => 'topic_sales#new', as: :new_topic
  get 'topico/ready/:id' => 'topic_sales#ready', as: :ready_topic
  post 'confirmtopico' => 'topic_sales#confirm', as: :confirm_topic
  post 'addtopico' => 'topic_sales#add', as: :add_topic
  post 'cerrartopico' => 'topic_sales#close', as: :close_topic
  post 'borrartopic' => 'topic_sales#delete', as: :delete_topic
  post 'borrarventatopico' => 'topic_sales#destroy', as: :destroy_topic

  get 'facturations/index'
  get 'facturas/autorizaciones/:page' => 'facturations#index', as: :authorizations_fact
  get 'facturations/new'
  get 'facturas/nuevo/:insured_id/:authorization_id' => 'facturations#new', as: :new_facturation
  get 'facturas/lista/:page' => 'facturations#list', as: :list_facturation
  get 'facturas/nuevo/ready/principal/:pay_document_id' => 'facturations#ready', as: :ready_principal_facturation
  get 'facturas/print/:id' => 'facturations#print', as: :print_facturation
  get 'facturas/nuevo/ready/prestacion/:pay_document_id' => 'facturations#benefit', as: :ready_benefit_facturation
  get 'facturas/nuevo/ready/asignacion/:pay_document_id' => 'facturations#asign', as: :ready_asign_facturation
  get 'facturas/nuevo/ready/asignados/:pay_document_id' => 'facturations#asigned', as: :ready_asigned_facturation
  get 'facturas/lotes/:page' => 'facturations#create_lot', as: :create_lot
  get 'facturas/exportar/proveedores' => 'facturations#providers', as: :facturation_providers
  get 'facturas/detalle_dental/:pay_document_id' => "facturations#new_dental", as: :new_dental
  get 'facturas/nueva_exportación' => "facturations#form_export_special", as: :form_export_special
  post 'facturas/generarlotes' => 'facturations#generate_lot', as: :generate_lot
  post 'facturas/confirmar' => 'facturations#confirm', as: :confirm_facturation
  post 'facturas/updateprincipal' => 'facturations#update_principal', as: :update_principal
  post 'facturas/updatebenefit' => 'facturations#update_benefit', as: :update_benefit
  post 'facturas/updateasign' => 'facturations#update_asign', as: :update_asign
  post 'facturas/agregarservicio' => 'facturations#add_detail_service', as: :add_detail_service
  post 'facturas/agregarfarmacia' => 'facturations#add_detail_pharmacy', as: :add_detail_pharmacy
  post 'facturas/agregarcobertura' => 'facturations#add_detail_coverage', as: :add_detail_coverage
  post 'facturas/borrarservicio' => 'facturations#delete_detail_service', as: :delete_detail_service
  post 'facturas/borrarfarmacia' => 'facturations#delete_detail_pharmacy', as: :delete_detail_pharmacy
  post 'facturas/borrarcobertura' => 'facturations#delete_detail_coverage', as: :delete_detail_coverage
  post 'facturas/cerrarfactura' => 'facturations#close_facture', as: :close_facture
  post 'facturas/add_dental' => 'facturations#add_dental', as: :add_dental
  post 'facturas/delete_dental' => 'facturations#delete_dental', as: :delete_dental
  post 'facturas/export_conta_nuevo' => 'facturations#new_export_facturation', as: :new_export_facturation
  
  post 'facturas/borrarfactura' => 'facturations#delete', as: :delete_facturation
  post 'facturas/modificarmontoneto' => 'facturations#update_amount', as: :update_amount
  post 'facturas/borrarlote' => 'facturations#delete_lot', as: :delete_lot
  post 'facturas/exportar' =>'facturations#export', as: :export
  post 'facturas/exportar_lote' =>'facturations#export_lot', as: :export_lot
  post 'facturas/asignar_todo' => 'facturations#asign_all', as: :asign_all
  get 'facturas/contabilidad'=> 'facturations#form_accounting', as: :form_accounting
  post 'facturas/exportar_contabilidad'=> 'facturations#export_accounting', as: :export_accounting 
  post 'facturas/corregir_productos'=> 'facturations#fix', as: :fix 
  post 'facturas/corregir_servicios'=> 'facturations#fix_service', as: :fix_service
  post 'facturas/corregir_productos_facturados'=> 'facturations#fix_facturated', as: :fix_facturated
  post 'facturas/get_checked'=> 'facturations#get_checked', as: :get_checked
  post 'facturas/get_unchecked'=> 'facturations#get_unchecked', as: :get_unchecked
  post 'facturas/generate_exportation' => 'facturations#generate_exportation', as: :generate_exportation
  post 'facturas/create_manual' => 'facturations#create_manual', as: :create_manual
  post 'facturas/add_manual_service' => 'facturations#add_manual_service', as: :add_manual_service
  
  get 'facturations/show'

  get 'pharmacy_sales/new'

  get 'pharmacy_sales/ready'

  get 'images/index'

  get 'images/recents'

  get 'images/show'

  get 'cash/index'

  get 'cash/recent' 

  get '/caja/:type/:page' => 'cash#index', as: :cash
  get '/caja/recientes' => 'cash#recent', as: :cash_recents

  get '/administracion' => 'administrations#index', as: :administration
  get '/trama' => 'administrations#trama', as: :trama
  get '/test' => 'administrations#test', as: :test
  get '/estadisticas' => 'administrations#stadistics', as: :stadistics
  get '/administracion/exportar_servicios' => 'administrations#show_export', as: :show_export
  get '/personal' => 'employees#index', as: :employees
  
  post '/export_services' => 'administrations#export_services', as: :export_services


  get '/about' => 'help#index', as: :help
  get '/faq' => 'help#faq', as: :faq

  get 'service_sales/index'

  get 'service_sales/show'
  
  get 'service_sales/new'

  get '/caja/servicio/:name/:id_authorization/' => "service_sales#new", as: :new_sales
  get '/caja/servicio/crear/ready/:id_sale' => "service_sales#ready_sales", as: :new_sales_ready
  get 'caja/impresion/convenio/:insured_service_id'=> "service_sales#print" , as: :print_services

  get '/caja/servicios/todos/:authorization_id' => 'service_sales#all', as: :insured_services_all
  post '/cambiarcodigonombre' => 'service_sales#change_name_code', as: :change_name_code
  post '/close_sale' => "service_sales#close_sale", as: :close_sale
  post '/open_sale' => "service_sales#open_sale", as: :open_sale
  post '/caja/nuevo/:name/:id_authorization/confirm' => "service_sales#confirm_sale", as: :confirm_sale
  post '/add_service' => "service_sales#add_service", as: :add_service
  post '/add_service_from_all' => "service_sales#add_all", as: :add_all_service
  post '/delete_service' => "service_sales#delete_service", as: :delete_service
  post '/delete_service_sale' => "service_sales#delete_service_sale", as: :delete_service_sale
  post '/modify_purchase_service' => "service_sales#update_purchase_service", as: :update_purchase_service  
  post '/cambiarservicioselect' => "service_sales#update_service", as: :update_service
  post '/cambiarunitariotext' => "service_sales#update_unitary", as: :update_unitary
  post '/cambiarnombreservicios' => "service_sales#update_name", as: :update_name_service
  post '/cambiarcodigoservicios' => "service_sales#update_code", as: :update_code_service
  post '/borrarserviciovistatodos' => "service_sales#delete_from_all", as: :delete_from_all
  post '/update_all_purchase' => "service_sales#update_all", as: :update_all_services

  get 'particular_service_sales/index'

  get 'particular_service_sales/show'

  get 'particular_service_sales/new'
  
  get '/caja/servicioparticular/:name/:id_authorization/' => "particular_service_sales#new", as: :new_sales_particular
  get '/caja/servicioparticular/crear/ready/:id_sale' => "particular_service_sales#ready_sales", as: :new_sales_ready_particular
  post '/cambiarcodigonombreparticular' => 'particular_service_sales#change_name_code', as: :change_name_code_particular
  post '/close_sale_particular_test' => "particular_service_sales#close_sale", as: :close_sale_particular
  post '/open_sale_particular' => "particular_service_sales#open_sale", as: :open_sale_particular
  post '/caja/nuevoservicioparticular/:name/:id_authorization/confirm' => "particular_service_sales#confirm_sale", as: :confirm_sale_particular
  post '/add_particular_service' => "particular_service_sales#add_service", as: :add_service_particular

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
	before_action :set_client, only: [:update, :edit, :update_factors]

	def index
		@clients = Insurance.order(id: :desc).where(show: true)
		@client = Insurance.new
	end

	def create
		@client = Insurance.create(client_params)
	end

	def edit
		@factors = @client.factors
	end

	def update
		@client.update(client_params)
	end

	def update_factors
		@client.update_factors(params.select{ |key| key.to_s.include? 'factor' }.values)
	end

	private

	def client_params
		params.require(:insurance).permit(:name, :code, :ruc, :consultation, :address)
	end

	def set_client
		@client = Insurance.find(params[:client_id])
	end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/partials/clients/_errors.html.haml
- if client.errors.any?
	%ul.list-group
		- client.errors.full_messages.each do |msg|
			%li.list-group-item.list-group-item-danger
				= msg
- else
	%ul.list-group
		%li.list-group-item.list-group-item-success Información de cliente guardada con éxito

app/views/partials/clients/_form.html.haml
#error_explanation
= form_for(@client, url: clients_create_path, remote: true) do |f|
	= f.label :name, 'Razón Social'
	= f.text_field :name, { class: 'form-control' }
	= f.label :code, 'Código'
	= f.text_field :code, { class: 'form-control' }
	= f.label :ruc, 'Ruc'
	= f.text_field :ruc, { class: 'form-control' }
	= f.label :consultation, 'Valor de consulta'
	= f.text_field :consultation, { class: 'form-control' }
	= f.label :address, 'Dirección'
	= f.text_field :address, { class: 'form-control' }
	.text-center
		= f.submit 'Guardar', { class: 'btn btn-primary top-buffer' }

app/views/partials/clients/_form_update.html.haml
#error_explanation
= form_for(@client, url: clients_update_path, method: 'post', remote: true) do |f|
	= hidden_field_tag :client_id, @client.id
	= f.label :name, 'Razón Social'
	= f.text_field :name, { class: 'form-control' }
	= f.label :code, 'Código'
	= f.text_field :code, { class: 'form-control' }
	= f.label :ruc, 'Ruc'
	= f.text_field :ruc, { class: 'form-control' }
	= f.label :consultation, 'Valor de consulta'
	= f.text_field :consultation, { class: 'form-control' }
	= f.label :address, 'Dirección'
	= f.text_field :address, { class: 'form-control' }
	.text-center
		= f.submit 'Guardar', { class: 'btn btn-primary top-buffer' }
= form_tag(clients_update_factors_path, method: 'post') do
	= hidden_field_tag :client_id, @client.id
	.row
		- @factors.each do |factor|
			.col-md-6
				= label_tag "factor_#{factor.clinic_area.id}", "Factor de #{factor.clinic_area.name}"
				= text_field_tag "factor_#{factor.clinic_area.id}", factor.factor, { class: 'form-control' }
	.text-center
		= submit_tag 'Guardar', { class: 'btn btn-primary top-buffer' }

app/views/partials/clients/_row.html.haml
%tr.reduce_row{ class: my_class}
	%td= client.id
	%td= link_to client.name, clients_edit_path(client_id: client.id), remote: true
	%td= client.code
	%td= client.ruc
	%td= client.consultation
	%td= client.address
	%td.dropdown
		%button#dropdownfactors.btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
			Ver Factores
			%span.caret
		%ul.dropdown-menu{"aria-labelledby" => "dropdownfactors", :role => "menu"}
			- client.factors.each do |factor|
				%li{:role => "presentation"}= link_to "#{factor.factor} Factor #{factor.clinic_area.name}", '#', role: 'menuitem', tabindex: '-1'