config/routes.rb
Rails.application.routes.draw do

  namespace :clients do
    get 'index'
    post 'create'
    post 'update'
    get 'edit'
    post 'update_factors'
  end

  get 'employees/index'

  get 'services/index'
  get 'servicios/:page' => 'services#index', as: :services
  post 'change_contable_code' => 'services#update_contable_code', as: :update_contable_code
  post '/nuevo_Servicio' => 'services#create', as: :create_service
  post '/borrar_Servicio' => 'services#delete', as: :delete_myservice
  get '/doctores' => 'doctors#index', as: :doctors

  get 'doctors/show'

  get 'doctors/new'

  get 'doctors/edit'
  post '/agregar_doctor' => 'doctors#create', as: :create_doctor
  post '/modificar_doctor' => 'doctors#update', as: :update_doctor
  post '/eliminar_doctor' => 'doctors#delete', as: :delete_doctor


  post '/agregar_especialidad' => 'doctors#create_speciality', as: :create_speciality

  get 'chat_csl/:page' => 'chat#index', as: :chat
  post 'agregarmensaje' => 'chat#add', as: :add_chat

  get 'admissions/new'
  #get 'admisiones/nuevo/:patient_id' => 'admissions#new', as: :new_admission
  get 'admissions/ready'
  get 'admision/ready/:authorization_id' => 'admissions#ready', as: :ready_admission
  post 'confirmar_admision' => 'admissions#confirm', as: :confirm_admission
  get 'admissions/index'

  get 'admission/new'


  get 'admission/ready'

  get 'admission/index'

  resources :providers

  get 'topic_sales/new'

  get 'topic_sales/ready'

  get 'cobertura/nuevo/:id' => 'coverage_sales#new', as: :new_coverage
  get 'cobertura/ready/:id' => 'coverage_sales#ready', as: :ready_coverage
  post 'confirmcobertura' => 'coverage_sales#confirm', as: :confirm_coverage
  post 'addcobertura' => 'coverage_sales#add', as: :add_coverage
  post 'cerrarcobertura' => 'coverage_sales#close', as: :close_coverage
  post 'borrarconsulta' => 'coverage_sales#delete', as: :delete_coverage
  post 'fastcoverage' => 'coverage_sales#fast_close', as: :fast_close

  get 'topico/nuevo/:id_authorization' => 'topic_sales#new', as: :new_topic
  get 'topico/ready/:id' => 'topic_sales#ready', as: :ready_topic
  post 'confirmtopico' => 'topic_sales#confirm', as: :confirm_topic
  post 'addtopico' => 'topic_sales#add', as: :add_topic
  post 'cerrartopico' => 'topic_sales#close', as: :close_topic
  post 'borrartopic' => 'topic_sales#delete', as: :delete_topic
  post 'borrarventatopico' => 'topic_sales#destroy', as: :destroy_topic

  get 'facturations/index'
  get 'facturas/autorizaciones/:page' => 'facturations#index', as: :authorizations_fact
  get 'facturations/new'
  get 'facturas/nuevo/:insured_id/:authorization_id' => 'facturations#new', as: :new_facturation
  get 'facturas/lista/:page' => 'facturations#list', as: :list_facturation
  get 'facturas/nuevo/ready/principal/:pay_document_id' => 'facturations#ready', as: :ready_principal_facturation
  get 'facturas/print/:id' => 'facturations#print', as: :print_facturation
  get 'facturas/nuevo/ready/prestacion/:pay_document_id' => 'facturations#benefit', as: :ready_benefit_facturation
  get 'facturas/nuevo/ready/asignacion/:pay_document_id' => 'facturations#asign', as: :ready_asign_facturation
  get 'facturas/nuevo/ready/asignados/:pay_document_id' => 'facturations#asigned', as: :ready_asigned_facturation
  get 'facturas/lotes/:page' => 'facturations#create_lot', as: :create_lot
  get 'facturas/exportar/proveedores' => 'facturations#providers', as: :facturation_providers
  get 'facturas/detalle_dental/:pay_document_id' => "facturations#new_dental", as: :new_dental
  get 'facturas/nueva_exportación' => "facturations#form_export_special", as: :form_export_special
  post 'facturas/generarlotes' => 'facturations#generate_lot', as: :generate_lot
  post 'facturas/confirmar' => 'facturations#confirm', as: :confirm_facturation
  post 'facturas/updateprincipal' => 'facturations#update_principal', as: :update_principal
  post 'facturas/updatebenefit' => 'facturations#update_benefit', as: :update_benefit
  post 'facturas/updateasign' => 'facturations#update_asign', as: :update_asign
  post 'facturas/agregarservicio' => 'facturations#add_detail_service', as: :add_detail_service
  post 'facturas/agregarfarmacia' => 'facturations#add_detail_pharmacy', as: :add_detail_pharmacy
  post 'facturas/agregarcobertura' => 'facturations#add_detail_coverage', as: :add_detail_coverage
  post 'facturas/borrarservicio' => 'facturations#delete_detail_service', as: :delete_detail_service
  post 'facturas/borrarfarmacia' => 'facturations#delete_detail_pharmacy', as: :delete_detail_pharmacy
  post 'facturas/borrarcobertura' => 'facturations#delete_detail_coverage', as: :delete_detail_coverage
  post 'facturas/cerrarfactura' => 'facturations#close_facture', as: :close_facture
  post 'facturas/add_dental' => 'facturations#add_dental', as: :add_dental
  post 'facturas/delete_dental' => 'facturations#delete_dental', as: :delete_dental
  post 'facturas/export_conta_nuevo' => 'facturations#new_export_facturation', as: :new_export_facturation
  
  post 'facturas/borrarfactura' => 'facturations#delete', as: :delete_facturation
  post 'facturas/modificarmontoneto' => 'facturations#update_amount', as: :update_amount
  post 'facturas/borrarlote' => 'facturations#delete_lot', as: :delete_lot
  post 'facturas/exportar' =>'facturations#export', as: :export
  post 'facturas/exportar_lote' =>'facturations#export_lot', as: :export_lot
  post 'facturas/asignar_todo' => 'facturations#asign_all', as: :asign_all
  get 'facturas/contabilidad'=> 'facturations#form_accounting', as: :form_accounting
  post 'facturas/exportar_contabilidad'=> 'facturations#export_accounting', as: :export_accounting 
  post 'facturas/corregir_productos'=> 'facturations#fix', as: :fix 
  post 'facturas/corregir_servicios'=> 'facturations#fix_service', as: :fix_service
  post 'facturas/corregir_productos_facturados'=> 'facturations#fix_facturated', as: :fix_facturated
  post 'facturas/get_checked'=> 'facturations#get_checked', as: :get_checked
  post 'facturas/get_unchecked'=> 'facturations#get_unchecked', as: :get_unchecked
  post 'facturas/generate_exportation' => 'facturations#generate_exportation', as: :generate_exportation
  post 'facturas/create_manual' => 'facturations#create_manual', as: :create_manual
  post 'facturas/add_manual_service' => 'facturations#add_manual_service', as: :add_manual_service
  
  get 'facturations/show'

  get 'pharmacy_sales/new'

  get 'pharmacy_sales/ready'

  get 'images/index'

  get 'images/recents'

  get 'images/show'

  get 'cash/index'

  get 'cash/recent' 

  get '/caja/:type/:page' => 'cash#index', as: :cash
  get '/caja/recientes' => 'cash#recent', as: :cash_recents

  get '/administracion' => 'administrations#index', as: :administration
  get '/trama' => 'administrations#trama', as: :trama
  get '/test' => 'administrations#test', as: :test
  get '/estadisticas' => 'administrations#stadistics', as: :stadistics
  get '/administracion/exportar_servicios' => 'administrations#show_export', as: :show_export
  get '/personal' => 'employees#index', as: :employees
  
  post '/export_services' => 'administrations#export_services', as: :export_services


  get '/about' => 'help#index', as: :help
  get '/faq' => 'help#faq', as: :faq

  get 'service_sales/index'

  get 'service_sales/show'
  
  get 'service_sales/new'

  get '/caja/servicio/:name/:id_authorization/' => "service_sales#new", as: :new_sales
  get '/caja/servicio/crear/ready/:id_sale' => "service_sales#ready_sales", as: :new_sales_ready
  get 'caja/impresion/convenio/:insured_service_id'=> "service_sales#print" , as: :print_services

  get '/caja/servicios/todos/:authorization_id' => 'service_sales#all', as: :insured_services_all
  post '/cambiarcodigonombre' => 'service_sales#change_name_code', as: :change_name_code
  post '/close_sale' => "service_sales#close_sale", as: :close_sale
  post '/open_sale' => "service_sales#open_sale", as: :open_sale
  post '/caja/nuevo/:name/:id_authorization/confirm' => "service_sales#confirm_sale", as: :confirm_sale
  post '/add_service' => "service_sales#add_service", as: :add_service
  post '/add_service_from_all' => "service_sales#add_all", as: :add_all_service
  post '/delete_service' => "service_sales#delete_service", as: :delete_service
  post '/delete_service_sale' => "service_sales#delete_service_sale", as: :delete_service_sale
  post '/modify_purchase_service' => "service_sales#update_purchase_service", as: :update_purchase_service  
  post '/cambiarservicioselect' => "service_sales#update_service", as: :update_service
  post '/cambiarunitariotext' => "service_sales#update_unitary", as: :update_unitary
  post '/cambiarnombreservicios' => "service_sales#update_name", as: :update_name_service
  post '/cambiarcodigoservicios' => "service_sales#update_code", as: :update_code_service
  post '/borrarserviciovistatodos' => "service_sales#delete_from_all", as: :delete_from_all
  post '/update_all_purchase' => "service_sales#update_all", as: :update_all_services

  get 'particular_service_sales/index'

  get 'particular_service_sales/show'

  get 'particular_service_sales/new'
  
  get '/caja/servicioparticular/:name/:id_authorization/' => "particular_service_sales#new", as: :new_sales_particular
  get '/caja/servicioparticular/crear/ready/:id_sale' => "particular_service_sales#ready_sales", as: :new_sales_ready_particular
  post '/cambiarcodigonombreparticular' => 'particular_service_sales#change_name_code', as: :change_name_code_particular
  post '/close_sale_particular_test' => "particular_service_sales#close_sale", as: :close_sale_particular
  post '/open_sale_particular' => "particular_service_sales#open_sale", as: :open_sale_particular
  post '/caja/nuevoservicioparticular/:name/:id_authorization/confirm' => "particular_service_sales#confirm_sale", as: :confirm_sale_particular
  post '/add_particular_service' => "particular_service_sales#add_service", as: :add_service_particular

app/controllers/topic_sales_controller.rb
class TopicSalesController < ApplicationController
  def new
  	@authorization = Authorization.find(params[:id_authorization])
    @doctors = to_hash_doctor(Doctor.all.order(:complet_name))
  end

  def delete
    p = PurchaseInsuredService.find(params[:purchase_insured_service_id])
    i = p.insured_service
    p.destroy
    redirect_to ready_topic_path(id: i.id)
  end

  def destroy
    i = InsuredService.find(params[:insured_service_id])
    a = i.authorization
    i.destroy
    redirect_to show_authorization_path(id: a.id)
  end

  def ready
  	@insured_service = InsuredService.find(params[:id])
  	@services = Service.where(clinic_area_id: 2).order(:name)
  	@service_exenteds = to_hash(ServiceExented.all)
  end

  def confirm
    d = Doctor.find(params[:doctor_id])
    if current_employee.area_id == 6
      i = InsuredService.create(authorization_id: params[:id_authorization], employee: current_employee, doctor_id: d.id, clinic_area_id: 2, has_ticket: false)
    else
      i = InsuredService.create(authorization_id: params[:id_authorization], employee: current_employee, doctor_id: d.id, clinic_area_id: 2, has_ticket: true)
    end  	
  	redirect_to ready_topic_path(id: i.id)
  end

  def add
  	p = PurchaseInsuredService.new
  	p.service_id = params[:service_id]
  	p.insured_service_id = params[:insured_service_id]
  	p.quantity = params[:quantity]
  	p.unitary = params[:price]
    p.service_exented_id = params[:service_exented_id]
  	p.save
  	redirect_to ready_topic_path(id: p.insured_service.id)
  end


  def to_hash_doctor(query)
    hash = Hash.new
    query.each do |q|
      hash[q.complet_name] = q.id
    end
    hash
  end


  def close
  	i = InsuredService.find(params[:id])
  	i.is_closed = params[:is_closed]
  	i.purchase_insured_services.each do |p|
  		i.initial_amount = i.initial_amount.to_f + p.initial_amount.to_f
  		i.copayment= i.copayment.to_f + p.copayment.to_f
  		i.igv = i.igv.to_f + p.igv.to_f
  		i.final_amount = i.final_amount.to_f + p.final_amount.to_f
	  end  
  	i.save
  	redirect_to ready_topic_path(id: i.id)
  end
end

app/helpers/topic_sales_helper.rb
module TopicSalesHelper
end

app/views/topic_sales/new.html.erb
<h1>Registro de Servicios de Tópico : 	</h1>
<p>¿Confirma que desea ingresar una nueva venta?</p>
<p>
	<%= form_tag(confirm_topic_path, method: 'post') do %>
		<%= hidden_field_tag :id_authorization, params[:id_authorization] %>
		<%= hidden_field_tag :name, params[:name] %>		
		<%= label_tag :doctor_id , 'Doctor encargado' %>
		<%= select_tag :doctor_id, options_for_select(@doctors) %>
		<%=submit_tag 'Confirmar', data: {confirm: '¿Está seguro que desea empezar una compra?'} %>
	<% end %>
</p>

app/views/topic_sales/new.html.haml
%h1 Registro de Servicios de Tópico :
%p ¿Confirma que desea ingresar una nueva venta?
%p
  = form_tag(confirm_topic_path, method: 'post') do
    = hidden_field_tag :id_authorization, params[:id_authorization]
    = hidden_field_tag :name, params[:name]
    = label_tag :doctor_id , 'Doctor encargado'
    = select_tag :doctor_id, options_for_select(@doctors)
    = submit_tag 'Confirmar', data: {confirm: '¿Está seguro que desea empezar una compra?'}

app/views/topic_sales/ready.html.erb
<div class="row">
	<div class="md-col-2"></div>
	<div class="md-col-8">
		<h1>Venta en tópico <%= @insured_service.ticket_code %></h1>
		<div class="row">
			<div class="col-md-5">
				<%= form_tag(destroy_topic_path, method: 'post', role: 'form') do %>
				<%= hidden_field_tag :insured_service_id, @insured_service.id %>
				<%= submit_tag 'Eliminar Venta', class: 'btn btn-danger' %>
				<% end %>
			</div>
		</div>
		<% if !@insured_service.is_closed %>
		<h3>Agregar Servicio</h3>
		<%= form_tag(add_topic_path, method: 'post') do %>
		<%= hidden_field_tag :insured_service_id, @insured_service.id %>
		<p>
			<%= label_tag :service_id , 'Elige el servicio' %>
			<%= select_tag :service_id, options_from_collection_for_select(@services, :id, :name) %>
		</p>
		<p>
			<%= label_tag :quantity , 'Cantidad' %>
			<%= number_field_tag :quantity %>
		</p>
		<p>
			<%= label_tag :price , 'Precio' %>
			<%= text_field_tag :price %>
		</p>
		<p>
			<%= label_tag :service_exented_id , 'Exonerado de Igv' %>
			<%= select_tag :service_exented_id, options_for_select(@service_exenteds) %>
		</p>
		<p>
			<%= submit_tag 'Agregar Servicio de Tópico', data: {confirm: '¿Está seguro que desea agregar el servicio?'} %>
		</p>
		<% end %>
		<% end %>

		<% if @insured_service.purchase_insured_services.exists? %>
		<table align="center" class="table table-bordered ">
			<thead>
				<tr align="center">
					<td>Código de servicio</td>
					<td>Nombre de servicio</td>
					<td>Cantidad</td>
					<td>Unitario</td>
					<td>Monto Inicial</td>
					<td>Aplicado Copago</td>
					<td>Igv</td>
					<td>Monto Final</td>
					<td>Borrar registro</td>
				</tr>
			</thead>
			<tbody>
				<% @insured_service.purchase_insured_services.each do |p| %>
				<tr align="center">
					<td><%= p.service.code %></td>
					<td><%= p.service.name %></td>
					<td><%= p.quantity.to_s %></td>
					<td><%= p.unitary %></td>
					<td><%= p.initial_amount %></td>
					<td><%= p.copayment %></td>
					<td><%= p.igv %></td>
					<td><%= p.final_amount %></td>
					<td></td>
				</tr>
				<% end %>

				<br><br>
				<% if @insured_service.is_closed %>				
				<tr align="center" class="info">
					<td colspan="4">TOTAL</td>
					<td><%= @insured_service.initial_amount %></td>
					<td><%= @insured_service.copayment %></td>
					<td><%= @insured_service.igv %></td>
					<td><%= @insured_service.final_amount %></td>
				</tr>
				<tr>
					<td align="center" colspan="8"><h1>Venta Cerrada</h1></td>					
				</tr>
				<% else %>
				<tr align="center">
					<td colspan="8">
						<%= form_tag(close_topic_path, method: 'post') do %>
						<%= hidden_field_tag :id, @insured_service.id %>
						<%= hidden_field_tag :is_closed, true %>
						<%= submit_tag 'Cerrar Venta', data: {confirm: '¿Está seguro que desea cerrar la compra?, no hay opción a cambio.'} %>
						<% end %>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<% else %>
		<p>No hay servicios agregados a esta venta</p>
		<% end %>

		<%= link_to 'Volver a perfil de Autorización', show_authorization_path(id: @insured_service.authorization.id) %>
	</div>
	<div class="md-col-2"></div>
</div>

app/views/topic_sales/ready.html.haml
.row
  .md-col-2
  .md-col-8
    %h1
      Venta en tópico #{@insured_service.ticket_code}
    .row
      .col-md-5
        = form_tag(destroy_topic_path, method: 'post', role: 'form') do
          = hidden_field_tag :insured_service_id, @insured_service.id
          = submit_tag 'Eliminar Venta', class: 'btn btn-danger'
    - if !@insured_service.is_closed
      %h3 Agregar Servicio
      = form_tag(add_topic_path, method: 'post') do
        = hidden_field_tag :insured_service_id, @insured_service.id
        %p
          = label_tag :service_id , 'Elige el servicio'
          = select_tag :service_id, options_from_collection_for_select(@services, :id, :name)
        %p
          = label_tag :quantity , 'Cantidad'
          = number_field_tag :quantity
        %p
          = label_tag :price , 'Precio'
          = text_field_tag :price
        %p
          = label_tag :service_exented_id , 'Exonerado de Igv'
          = select_tag :service_exented_id, options_for_select(@service_exenteds)
        %p
          = submit_tag 'Agregar Servicio de Tópico', data: {confirm: '¿Está seguro que desea agregar el servicio?'}
    - if @insured_service.purchase_insured_services.exists?
      %table.table.table-bordered{:align => "center"}
        %thead
          %tr{:align => "center"}
            %td Código de servicio
            %td Nombre de servicio
            %td Cantidad
            %td Unitario
            %td Monto Inicial
            %td Aplicado Copago
            %td Igv
            %td Monto Final
            %td Borrar registro
        %tbody
          - @insured_service.purchase_insured_services.each do |p|
            %tr{:align => "center"}
              %td= p.service.code
              %td= p.service.name
              %td= p.quantity.to_s
              %td= p.unitary
              %td= p.initial_amount
              %td= p.copayment
              %td= p.igv
              %td= p.final_amount
              %td
      %br/
      %br/
      - if @insured_service.is_closed
        %tr.info{:align => "center"}
          %td{:colspan => "4"} TOTAL
          %td= @insured_service.initial_amount
          %td= @insured_service.copayment
          %td= @insured_service.igv
          %td= @insured_service.final_amount
        %tr
          %td{:align => "center", :colspan => "8"}
            %h1 Venta Cerrada
      - else
        %tr{:align => "center"}
          %td{:colspan => "8"}
            = form_tag(close_topic_path, method: 'post') do
              = hidden_field_tag :id, @insured_service.id
              = hidden_field_tag :is_closed, true
              = submit_tag 'Cerrar Venta', data: {confirm: '¿Está seguro que desea cerrar la compra?, no hay opción a cambio.'}
    - else
      %p No hay servicios agregados a esta venta
    = link_to 'Volver a perfil de Autorización', show_authorization_path(id: @insured_service.authorization.id)
  .md-col-2