config/routes.rb
Rails.application.routes.draw do

  namespace :clients do
    get 'index'
    post 'create'
    post 'update'
    get 'edit'
    post 'update_factors'
  end

  get 'employees/index'

  get 'services/index'
  get 'servicios/:page' => 'services#index', as: :services
  post 'change_contable_code' => 'services#update_contable_code', as: :update_contable_code
  post '/nuevo_Servicio' => 'services#create', as: :create_service
  post '/borrar_Servicio' => 'services#delete', as: :delete_myservice
  get '/doctores' => 'doctors#index', as: :doctors

  get 'doctors/show'

  get 'doctors/new'

  get 'doctors/edit'
  post '/agregar_doctor' => 'doctors#create', as: :create_doctor
  post '/modificar_doctor' => 'doctors#update', as: :update_doctor
  post '/eliminar_doctor' => 'doctors#delete', as: :delete_doctor


  post '/agregar_especialidad' => 'doctors#create_speciality', as: :create_speciality

  get 'chat_csl/:page' => 'chat#index', as: :chat
  post 'agregarmensaje' => 'chat#add', as: :add_chat

  get 'admissions/new'
  #get 'admisiones/nuevo/:patient_id' => 'admissions#new', as: :new_admission
  get 'admissions/ready'
  get 'admision/ready/:authorization_id' => 'admissions#ready', as: :ready_admission
  post 'confirmar_admision' => 'admissions#confirm', as: :confirm_admission
  get 'admissions/index'

  get 'admission/new'


  get 'admission/ready'

  get 'admission/index'

  resources :providers

  get 'topic_sales/new'

  get 'topic_sales/ready'

  get 'cobertura/nuevo/:id' => 'coverage_sales#new', as: :new_coverage
  get 'cobertura/ready/:id' => 'coverage_sales#ready', as: :ready_coverage
  post 'confirmcobertura' => 'coverage_sales#confirm', as: :confirm_coverage
  post 'addcobertura' => 'coverage_sales#add', as: :add_coverage
  post 'cerrarcobertura' => 'coverage_sales#close', as: :close_coverage
  post 'borrarconsulta' => 'coverage_sales#delete', as: :delete_coverage
  post 'fastcoverage' => 'coverage_sales#fast_close', as: :fast_close

  get 'topico/nuevo/:id_authorization' => 'topic_sales#new', as: :new_topic
  get 'topico/ready/:id' => 'topic_sales#ready', as: :ready_topic
  post 'confirmtopico' => 'topic_sales#confirm', as: :confirm_topic
  post 'addtopico' => 'topic_sales#add', as: :add_topic
  post 'cerrartopico' => 'topic_sales#close', as: :close_topic
  post 'borrartopic' => 'topic_sales#delete', as: :delete_topic
  post 'borrarventatopico' => 'topic_sales#destroy', as: :destroy_topic

  get 'facturations/index'
  get 'facturas/autorizaciones/:page' => 'facturations#index', as: :authorizations_fact
  get 'facturations/new'
  get 'facturas/nuevo/:insured_id/:authorization_id' => 'facturations#new', as: :new_facturation
  get 'facturas/lista/:page' => 'facturations#list', as: :list_facturation
  get 'facturas/nuevo/ready/principal/:pay_document_id' => 'facturations#ready', as: :ready_principal_facturation
  get 'facturas/print/:id' => 'facturations#print', as: :print_facturation
  get 'facturas/nuevo/ready/prestacion/:pay_document_id' => 'facturations#benefit', as: :ready_benefit_facturation
  get 'facturas/nuevo/ready/asignacion/:pay_document_id' => 'facturations#asign', as: :ready_asign_facturation
  get 'facturas/nuevo/ready/asignados/:pay_document_id' => 'facturations#asigned', as: :ready_asigned_facturation
  get 'facturas/lotes/:page' => 'facturations#create_lot', as: :create_lot
  get 'facturas/exportar/proveedores' => 'facturations#providers', as: :facturation_providers
  get 'facturas/detalle_dental/:pay_document_id' => "facturations#new_dental", as: :new_dental
  get 'facturas/nueva_exportación' => "facturations#form_export_special", as: :form_export_special
  post 'facturas/generarlotes' => 'facturations#generate_lot', as: :generate_lot
  post 'facturas/confirmar' => 'facturations#confirm', as: :confirm_facturation
  post 'facturas/updateprincipal' => 'facturations#update_principal', as: :update_principal
  post 'facturas/updatebenefit' => 'facturations#update_benefit', as: :update_benefit
  post 'facturas/updateasign' => 'facturations#update_asign', as: :update_asign
  post 'facturas/agregarservicio' => 'facturations#add_detail_service', as: :add_detail_service
  post 'facturas/agregarfarmacia' => 'facturations#add_detail_pharmacy', as: :add_detail_pharmacy
  post 'facturas/agregarcobertura' => 'facturations#add_detail_coverage', as: :add_detail_coverage
  post 'facturas/borrarservicio' => 'facturations#delete_detail_service', as: :delete_detail_service
  post 'facturas/borrarfarmacia' => 'facturations#delete_detail_pharmacy', as: :delete_detail_pharmacy
  post 'facturas/borrarcobertura' => 'facturations#delete_detail_coverage', as: :delete_detail_coverage
  post 'facturas/cerrarfactura' => 'facturations#close_facture', as: :close_facture
  post 'facturas/add_dental' => 'facturations#add_dental', as: :add_dental
  post 'facturas/delete_dental' => 'facturations#delete_dental', as: :delete_dental
  post 'facturas/export_conta_nuevo' => 'facturations#new_export_facturation', as: :new_export_facturation
  
  post 'facturas/borrarfactura' => 'facturations#delete', as: :delete_facturation
  post 'facturas/modificarmontoneto' => 'facturations#update_amount', as: :update_amount
  post 'facturas/borrarlote' => 'facturations#delete_lot', as: :delete_lot
  post 'facturas/exportar' =>'facturations#export', as: :export
  post 'facturas/exportar_lote' =>'facturations#export_lot', as: :export_lot
  post 'facturas/asignar_todo' => 'facturations#asign_all', as: :asign_all
  get 'facturas/contabilidad'=> 'facturations#form_accounting', as: :form_accounting
  post 'facturas/exportar_contabilidad'=> 'facturations#export_accounting', as: :export_accounting 
  post 'facturas/corregir_productos'=> 'facturations#fix', as: :fix 
  post 'facturas/corregir_servicios'=> 'facturations#fix_service', as: :fix_service
  post 'facturas/corregir_productos_facturados'=> 'facturations#fix_facturated', as: :fix_facturated
  post 'facturas/get_checked'=> 'facturations#get_checked', as: :get_checked
  post 'facturas/get_unchecked'=> 'facturations#get_unchecked', as: :get_unchecked
  post 'facturas/generate_exportation' => 'facturations#generate_exportation', as: :generate_exportation
  post 'facturas/create_manual' => 'facturations#create_manual', as: :create_manual
  post 'facturas/add_manual_service' => 'facturations#add_manual_service', as: :add_manual_service
  
  get 'facturations/show'

  get 'pharmacy_sales/new'

  get 'pharmacy_sales/ready'

  get 'images/index'

  get 'images/recents'

  get 'images/show'

  get 'cash/index'

  get 'cash/recent' 

  get '/caja/:type/:page' => 'cash#index', as: :cash
  get '/caja/recientes' => 'cash#recent', as: :cash_recents

  get '/administracion' => 'administrations#index', as: :administration
  get '/trama' => 'administrations#trama', as: :trama
  get '/test' => 'administrations#test', as: :test
  get '/estadisticas' => 'administrations#stadistics', as: :stadistics
  get '/administracion/exportar_servicios' => 'administrations#show_export', as: :show_export
  get '/personal' => 'employees#index', as: :employees
  
  post '/export_services' => 'administrations#export_services', as: :export_services


  get '/about' => 'help#index', as: :help
  get '/faq' => 'help#faq', as: :faq

  get 'service_sales/index'

  get 'service_sales/show'
  
  get 'service_sales/new'

  get '/caja/servicio/:name/:id_authorization/' => "service_sales#new", as: :new_sales
  get '/caja/servicio/crear/ready/:id_sale' => "service_sales#ready_sales", as: :new_sales_ready
  get 'caja/impresion/convenio/:insured_service_id'=> "service_sales#print" , as: :print_services

  get '/caja/servicios/todos/:authorization_id' => 'service_sales#all', as: :insured_services_all
  post '/cambiarcodigonombre' => 'service_sales#change_name_code', as: :change_name_code
  post '/close_sale' => "service_sales#close_sale", as: :close_sale
  post '/open_sale' => "service_sales#open_sale", as: :open_sale
  post '/caja/nuevo/:name/:id_authorization/confirm' => "service_sales#confirm_sale", as: :confirm_sale
  post '/add_service' => "service_sales#add_service", as: :add_service
  post '/add_service_from_all' => "service_sales#add_all", as: :add_all_service
  post '/delete_service' => "service_sales#delete_service", as: :delete_service
  post '/delete_service_sale' => "service_sales#delete_service_sale", as: :delete_service_sale
  post '/modify_purchase_service' => "service_sales#update_purchase_service", as: :update_purchase_service  
  post '/cambiarservicioselect' => "service_sales#update_service", as: :update_service
  post '/cambiarunitariotext' => "service_sales#update_unitary", as: :update_unitary
  post '/cambiarnombreservicios' => "service_sales#update_name", as: :update_name_service
  post '/cambiarcodigoservicios' => "service_sales#update_code", as: :update_code_service
  post '/borrarserviciovistatodos' => "service_sales#delete_from_all", as: :delete_from_all
  post '/update_all_purchase' => "service_sales#update_all", as: :update_all_services

  get 'particular_service_sales/index'

  get 'particular_service_sales/show'

  get 'particular_service_sales/new'
  
  get '/caja/servicioparticular/:name/:id_authorization/' => "particular_service_sales#new", as: :new_sales_particular
  get '/caja/servicioparticular/crear/ready/:id_sale' => "particular_service_sales#ready_sales", as: :new_sales_ready_particular
  post '/cambiarcodigonombreparticular' => 'particular_service_sales#change_name_code', as: :change_name_code_particular
  post '/close_sale_particular_test' => "particular_service_sales#close_sale", as: :close_sale_particular
  post '/open_sale_particular' => "particular_service_sales#open_sale", as: :open_sale_particular
  post '/caja/nuevoservicioparticular/:name/:id_authorization/confirm' => "particular_service_sales#confirm_sale", as: :confirm_sale_particular
  post '/add_particular_service' => "particular_service_sales#add_service", as: :add_service_particular

app/models/authorization_type.rb
class AuthorizationType < ActiveRecord::Base
end

app/controllers/authorizations_controller.rb
class AuthorizationsController < ApplicationController
  respond_to :html, :js
  before_action :block_unloged
  before_action :set_authorization, only: [:set_id_correlative, :show, :clear_data, :edit_code, :asign_to_me, :update_history_code, :update_dni_authorization]

  def index  	
    if params[:authorization_code].nil? and params[:paternal].nil?
      @authorizations = Authorization.order('convert(intern_code, decimal) DESC').paginate(:page => params[:page])
    else
      if params[:paternal].nil?
        @authorizations = Authorization.where('code like "%'+ params[:authorization_code] + '%"').order('convert(intern_code, decimal) DESC').paginate(:page => params[:page])  
      else
        @authorizations = Authorization.all.joins(:patient).where('patients.paternal like "%'+params[:paternal] +'%" and patients.maternal like "%'+params[:maternal] +'%"').order('convert(intern_code, decimal) DESC').paginate(:page => params[:page])  
      end            
    end
    @statuses = to_hash(Status.all)
    respond_to do |format|
      format.js
      format.html
    end
  end

  def export
    @authorizations = Authorization.where('date(date) = "'+params[:date]+'"').order(:intern_code)
  end

  def set_id_correlative
    @code = @authorization.id.to_s
  end
  
  def show
  	@statuses = Status.all
  	@doctors = get_doctor_hash(Doctor.all.order(:complet_name))
    @diagnostic_categories = DiagnosticCategory.order(:name)
    @diagnostic_types = get_diagnostic_hash(DiagnosticType.all.order(:name))
    @diagnostic_types_codes = get_diagnostic_code_hash(DiagnosticType.all.order(:id))
    @hospitalization_types = to_hash(HospitalizationType.all)
    @hospitalization_output_types = to_hash(HospitalizationOutputType.all)
    @dni = @authorization.patient.document_identity_code    
    @sub_coverage_types = get_subcoverage_hash(SubCoverageType.all.order(:name))
    @my_date = @authorization.date + 5.hours
    unless @authorization.coverage.nil? 
      unless @authorization.coverage.sub_coverage_type.nil?
        unless @authorization.coverage.sub_coverage_type.coverage_type.nil?
          @d = @my_date.strftime("%A")
          @j = @my_date.strftime("%H:%M:%S")
          @h = @my_date.strftime("%H").to_i
          @m = @my_date.strftime("%M").to_i
          if @h > 19  || @h < 8 || @d == "Sunday" || (@h > 14 and @d== "Saturday")
            @error="cobrar el recargo"
          end
        end
      end      
    end
  end
  
  def set_status
    @authorization = Authorization.find(params[:authorization_id])
    @authorization.status_id = params[:status_id]
    @authorization.save
    @authorizations = Authorization.order('convert(intern_code, decimal) DESC').paginate(:page => params[:page])
    @statuses = to_hash(Status.all)
    respond_to do |format|
      format.js
    end
  end

  def edit_code
    @authorization.code = params[:code]
    @authorization.save
    if @authorization.pay_documents.exists?
      @authorization.pay_documents.each do |p|
        b = p.benefit
        b.first_authorization_number = params[:code]
        b.save
      end
    end
    redirect_to show_authorization_path(id: params[:id])
  end

  def update_info
  	Authorization.update_info(params)
    @authorization = Authorization.find(params[:id])
    respond_to do |format|
      format.js
      format.html{redirect_to show_authorization_path(id: params[:id])}
    end
  end

  def update_diagnostics
    if params[:first_diagnostic_id].nil? or params[:first_diagnostic_id] == ""
      @first_diagnostic = nil
    else
      @first_diagnostic = DiagnosticType.find_by_code(params[:first_diagnostic_id]).code
    end

    if params[:second_diagnostic_id].nil? or params[:second_diagnostic_id] == ""
      @second_diagnostic = nil
    else
      @second_diagnostic = DiagnosticType.find_by_code(params[:second_diagnostic_id]).code
    end

    if params[:third_diagnostic_id].nil? or params[:third_diagnostic_id] == ""
      @third_diagnostic = nil
    else
      @third_diagnostic = DiagnosticType.find_by_code(params[:third_diagnostic_id]).code
    end    
    respond_to do |format|
      format.js
    end
  end

  def update_history_code
    patient = @authorization.patient
    patient.clinic_history_code = params[:clinic_history_code]
    patient.save
    respond_to do |format|
      format.js
    end
  end

  def update_dni_authorization
    @patient = @authorization.patient
    @patient.document_identity_code = params[:document_identity_code]
    @patient.save
    respond_to do |format|
      format.js
    end
  end

  def destroy
    a = Authorization.find(params[:authorization_id])
    a.destroy
    redirect_to authorizations_path(page: '1')
  end

  def clear_data
    @authorization.doctor_id = nil
    @authorization.first_diagnostic = nil
    @authorization.second_diagnostic = nil
    @authorization.third_diagnostic = nil
    @authorization.has_consultation = nil
    @authorization.save
    @authorization.insured_services.each do |i|
      i.destroy
    end
    @authorization.insured_pharmacies.each do |i|
      if i.pharm_type_sale_id == 1
        i.destroy
      end
    end
    @authorization.pay_documents.each do |p|
      p.destroy
    end
    respond_to do |format|
      format.html { redirect_to show_authorization_path(id: @authorization.id) }
      format.js
    end
  end

  def load
    @patients = Patient.where(paternal: params[:paternal], maternal: params[:maternal])
    @authorization = Authorization.find(params[:authorization_id])
    respond_to do |format|
      format.html { redirect_to show_authorization_path(id: @authorization.id) }
      format.js
    end
  end

  def asign_to_me
    @authorization.employee = current_employee
    @authorization.save
    @employee = current_employee.username
    @buton_name = 'btn' + @authorization.id.to_s
    respond_to do |format|
      format.html { redirect_to authorizations_path(page: '1') }
      format.js 
    end
  end
  
  def fix
    @authorization = Authorization.find(params[:authorization_id])
    patient = Patient.find(params[:patient_id])
    @authorization.patient = patient
    @authorization.save
    @authorizations = Authorization.order('convert(intern_code, decimal) DESC').paginate(:page => params[:page])
    respond_to do |format|
      format.html { redirect_to show_authorization_path(id: @authorization.id) }
      format.js
    end
  end

  def update_intern_code
    authorization = Authorization.find(params[:authorization_id])
    authorization.intern_code = params[:intern_code]
    authorization.save
    @authorizations = Authorization.order('convert(intern_code, decimal) DESC').paginate(:page => params[:page])
    @statuses = to_hash(Status.all)
    respond_to do |format|
      format.html { redirect_to show_authorization_path(id: @authorization.id) }
      format.js
    end
  end

  private

  def get_doctor_hash(query)
    hash = Hash.new
    query.each do |q|
      hash[q.complet_name] = q.id
    end
    hash
  end

  def get_subcoverage_hash(query)
    hash = Hash.new
    query.each do |q|
      hash[q.name + " - " + q.code + " - " + q.other_code] = q.id
    end
    hash
  end

  def get_diagnostic_code_hash(query)
    hash = Hash.new
    query.each do |q|
      hash[q.code.to_s] = q.code
    end
    hash
  end

  def get_diagnostic_hash(query)
    hash = Hash.new
    query.each do |q|
      hash[q.name.to_s[0,50] + '... '+ q.code.to_s] = q.code
    end
    hash
  end

  def set_authorization    
    @authorization = Authorization.find(params[:id])
  end

end

app/helpers/authorizations_helper.rb
module AuthorizationsHelper
end

app/views/authorizations/_add_consultation.html.erb
<div class="list-group">
	

	<h1>Registro de consulta médica</h1>
	<p>¿Confirma que desea ingresar una nueva venta?</p>
	<p>

		<div class="form-group">
			<%= hidden_field_tag :authorization_id, params[:id] %>
			<%=submit_tag 'Confirmar', {class: 'btn btn-primary', data: {confirm: '¿Está seguro que desea ingresar una cobertura?'}} %>
		</div>
		

		
		<div class="row">
			<div class="col-md-4">
				<div class="form-group">
					<%= text_field_tag :unitary, '', class: 'form-control' %>
				</div>
				<div class="form-group">
					<%= hidden_field_tag :authorization_id, params[:id] %>
					<%=submit_tag 'Agregado rápido', {class: 'btn btn-danger'} %>
				</div>
			</div>
		</div>	
		
	</p>
</div>

app/views/authorizations/_info_to_update.html.haml
- if can? :manage, Authorization
  .row
    .col-md-8
      .form-group
        = label_tag :first_diagnostic, 'Diagnóstico 1'
        = select_tag :first_diagnostic, options_for_select(@diagnostic_types,@authorization.first_diagnostic), {prompt: 'Seleccione el diagnóstico', class: 'form-control'}
    .col-md-4
      .form-group
        = label_tag :first_diagnostic_code, 'Diagnóstico 1'
        = select_tag :first_diagnostic_code, options_for_select(@diagnostic_types_codes,@authorization.first_diagnostic), {prompt: 'Por código', class: 'form-control'}
  .row
    .col-md-8
      .form-group
        = label_tag :second_diagnostic, 'Diagnóstico 2'
        = select_tag :second_diagnostic, options_for_select(@diagnostic_types,@authorization.second_diagnostic), {prompt: 'Seleccione el diagnóstico', class: 'form-control'}
    .col-md-4
      .form-group
        = label_tag :second_diagnostic_code, 'Diagnóstico 2'
        = select_tag :second_diagnostic_code, options_for_select(@diagnostic_types_codes,@authorization.second_diagnostic), {prompt: 'Por código', class: 'form-control'}
  .row
    .col-md-8
      .form-group
        = label_tag :third_diagnostic, 'Diagnóstico 3'
        = select_tag :third_diagnostic, options_for_select(@diagnostic_types,@authorization.third_diagnostic), {prompt: 'Seleccione el diagnóstico', class: 'form-control'}
    .col-md-4
      .form-group
        = label_tag :third_diagnostic_code, 'Diagnóstico 3'
        = select_tag :third_diagnostic_code, options_for_select(@diagnostic_types_codes,@authorization.third_diagnostic), {prompt: 'Por código', class: 'form-control'}
- else
  = hidden_field_tag :first_diagnostic, @authorization.first_diagnostic
  = hidden_field_tag :first_diagnostic_code, @authorization.first_diagnostic
  = hidden_field_tag :second_diagnostic, @authorization.second_diagnostic
  = hidden_field_tag :second_diagnostic_code, @authorization.second_diagnostic
  = hidden_field_tag :third_diagnostic, @authorization.third_diagnostic
  = hidden_field_tag :third_diagnostic_code, @authorization.third_diagnostic

app/views/authorizations/_links_insured.html.haml
.jumbotron
  .container
    .list-group
      = link_to 'AGREGAR SERVICIOS', '#', class: "list-group-item active", remote: true
      = link_to 'Agregar Exámen de Laboratorio', new_sales_path(name: ClinicArea.find(4).name, id_authorization: @authorization.id), class: "list-group-item" if can? :manage, InsuredService
      = link_to 'Agregar Exámen de Rayos X', new_sales_path(name: ClinicArea.find(5).name, id_authorization: @authorization.id), class: "list-group-item" if can? :manage, InsuredService
      = link_to 'Agregar Ecografía', new_sales_path(name: ClinicArea.find(6).name, id_authorization: @authorization.id), class: "list-group-item" if can? :manage, InsuredService
      = link_to 'Agregar Tomografía', new_sales_path(name: ClinicArea.find(7).name, id_authorization: @authorization.id), class: "list-group-item" if can? :manage, InsuredService
      = link_to 'Agregar procedimiento', new_sales_path(name: ClinicArea.find(3).name, id_authorization: @authorization.id), class: "list-group-item" if can? :manage, InsuredService
      = link_to 'Agregar odontológico', new_sales_path(name: ClinicArea.find(8).name, id_authorization: @authorization.id), class: "list-group-item" if can? :manage, InsuredService
      = link_to 'Agregar Procedimiento quirúrgico', new_sales_path(name: ClinicArea.find(1).name, id_authorization: @authorization.id), class: "list-group-item" if can? :manage, InsuredService
      = link_to 'Agregar Productos de tópico', new_topic_path(id_authorization: @authorization.id), class: "list-group-item" if can? :manage, InsuredService
      = link_to 'Agregar Productos Farmacéuticos', new_pharmacy_path(id_authorization: @authorization.id), class: "list-group-item"
      = link_to 'Vista Total', insured_services_all_path(authorization_id: @authorization.id), class: "list-group-item"
      - unless @authorization.has_consultation
        = link_to 'Agregar Consulta', '#', class: "list-group-item", data: {toggle: 'modal', target: '#consulta'} if can? :manage, InsuredService
#consulta.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} &times;
      .modal-body
        %h1 Registro de consulta médica
        %p ¿Confirma que desea ingresar una nueva venta?
        %p
          = form_tag('#', method: 'post') do
            .form-group
              = hidden_field_tag :authorization_id, params[:id]
              = submit_tag 'Confirmar', {class: 'btn btn-primary', data: { confirm: 'Está seguro que desea agregar una nueva consulta?'}}
          = form_tag(fast_close_path, method: 'post', remote: true) do
            .row
              .col-md-4
                .form-group
                  = text_field_tag :unitary, '', class: 'form-control'
                .form-group
                  = hidden_field_tag :authorization_id, params[:id]
                  = submit_tag 'Agregado rápido', {class: 'btn btn-danger'}

app/views/authorizations/_links_services.html.haml
.jumbotron
  .container
    .list-group
      = link_to 'VENTAS SERVICIOS', '#', class: "list-group-item active"
      - if @authorization.insured_services.exists?
        - @authorization.insured_services.each do |i|
          - if i.is_consultation == nil
            - if i.is_closed
              = link_to 'Visitar ' + i.clinic_area.name + ' Monto total ' + i.final_amount.to_s + ' ' + i.authorization.money.name + ' - ' + 'Doctor en error', new_sales_ready_path(id_sale: i.id), class: 'list-group-item list-group-item-success' if i.doctor.nil?
              = link_to 'Visitar ' + i.clinic_area.name + ' Monto total ' + i.final_amount.to_s + ' ' + i.authorization.money.name + ' - ' + i.doctor.complet_name, new_sales_ready_path(id_sale: i.id), class: 'list-group-item list-group-item-success' unless i.doctor.nil?
            - else
              = link_to 'Visitar ' + i.clinic_area.name + ' Monto total ' + i.final_amount.to_s + ' ' + i.authorization.money.name + ' - ' + i.doctor.complet_name, new_sales_ready_path(id_sale: i.id), class: 'list-group-item list-group-item-danger'
          - else
            - if i.is_closed
              = link_to 'Visitar ' + 'Costo por cobertura Monto total ' + i.final_amount.to_s + ' ' + i.authorization.money.name, ready_coverage_path(id: i.id), class: 'list-group-item list-group-item-success'
            - else
              = link_to 'Visitar ' + 'Costo por cobertura Monto total ' + i.final_amount.to_s + ' ' + i.authorization.money.name, ready_coverage_path(id: i.id), class: 'list-group-item list-group-item-danger'
      - else
        = link_to 'No existen ventas cerrads.', '#', class: "list-group-item"

app/views/authorizations/_loaded_patients.html.haml
%option Seleccione un paciente
- patients.each do |p| 
	%option{:value => "#{p.id}"}
		=p.full_name

app/views/authorizations/asign_to_me.js.erb
$("#<%= @buton_name %>").attr( "data-original-title", "<%= @employee %>" );
alert('Cambiado con éxito');

app/views/authorizations/clear_data.js.haml
alert('Información borrada correctamente');
$('#doctor_id').val('');
$('#first_diagnostic').val('');
$('#first_diagnostic_code').val('');
$('#second_diagnostic').val('');
$('#second_diagnostic_code').val('');
$('#third_diagnostic').val('');
$('#third_diagnostic_code').val('');

app/views/authorizations/index.js.erb
NProgress.start();
$('#table').html("<%= j (render 'table' )%>");
NProgress.done();

app/views/authorizations/index.js.haml
NProgress.start();
$('#table').html("#{j (render 'table' )}");
NProgress.done();

app/views/authorizations/recents.html.erb
<center><%= @authorizations.count %></center>
<table>
	<% @authorizations.each do |a| %>
		<tr>
			<td><%= a.id %></td>
			<td><%= link_to to_name_i(a.insured), show_insured_path(id: a.insured.id) %></td>
			<td><%= a.insured.insurance.name %></td>	
			<td><%= link_to 'ir a'+ a.code, show_authorization_path(id: a.id) %></td>
		</tr>
	<% end %>
</table>
<br>
<center><%= will_paginate @authorizations %></center>

app/views/authorizations/set_status.js.erb
$('#table').html('<%= j render "table" %>')

app/views/authorizations/update_diagnostics.js.erb
$("#first_diagnostic").val("<%= @first_diagnostic %>").change();
$("#second_diagnostic").val("<%= @second_diagnostic %>").change();
$("#third_diagnostic").val("<%= @third_diagnostic %>").change();

app/views/authorizations/update_history_code.js.erb
alert('Corregido con éxito')

app/views/authorizations/update_info.js.erb
alert('Información agregada correctamente');